
primaryColor=#E3E3DC
accentColor=#A9C78F
autoColor=true
use24HourClock=false
backgroundColor=#1A1C18
textColor=#E3E3DC
# Font settings
fontFamily=Inter,sans-serif
fontSize=11
# Virtual Keyboard
# If true, the virtual keyboard will be allowed to show. 
# If false, it will be explicitly hidden when the password field is focused.
forceVirtualKeyboard=false
